# fly.toml app configuration file for consulta-pe-telegram-bot
# Generated: 2025-09-20

app = "consulta-pe-telegram-bot"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Volume persistente para guardar la sesión de Telegram
[[mounts]]
source = "telegram-data"
destination = "/app/session"
