app = "consulta-pe-telegram-bot"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
source = "telegram-data"
destination = "/app/session"
